-- Update roles with correct activities
UPDATE role SET activities = 'HR_DASHBOARD,HR_EMPLOYEES,HR_ROLES,HR_LOGIN' WHERE role_name = 'HR';
UPDATE role SET activities = 'SUPERVISOR_ATTENDANCE,SUPERVISOR_ASSIGNMENTS,SUPERVISOR_EFFICIENCY,SUPERVISOR_JOBS,SUPERVISOR_QR_SCAN' WHERE role_name = 'SUPERVISOR';
UPDATE role SET activities = 'GM_DASHBOARD,GM_PRODUCTION,GM_EFFICIENCY,GM_REPORTS' WHERE role_name = 'GM';
UPDATE role SET activities = 'OPERATOR_SCAN,OPERATOR_EFFICIENCY,OPERATOR_DASHBOARD' WHERE role_name IN ('OPERATOR','CUTTER','STITCHER','IRONING','PACKAGER');
UPDATE role SET activities = 'QC_DEFECT_LOG,QC_VERIFICATION,QC_REWORK' WHERE role_name IN ('QC_ENGINEER','QC_MANAGER','QUALITY_CONTROL_ENGINEER','QUALITY_CONTROL_MANAGER');
UPDATE role SET activities = 'STORE_DISPATCH,STORE_RTM,STORE_STOCK' WHERE role_name = 'STORE_KEEPER';
UPDATE role SET activities = 'PROCESS_SAM_UPDATE,PROCESS_METHOD_STUDY,PROCESS_INDUSTRY_SAM' WHERE role_name = 'PROCESS_PLANNER';

SELECT role_id, role_name, activities FROM role;
